#! /usr/bin/bash 
#$ -m ea  
#$ -M jinhyun.ju@gmail.com
#$ -j y
#$ -cwd
#$ -pe smp 4
#$ -l "os=rhel6.3, zeno=true, h_vmem=30G"

DEFAULT_R_VERSION=3.2.0
RPATH=/zenodotus/dat01/mezeylab_store/mezeysoft/bin/
PYTHONPATH=/zenodotus/dat01/mezeylab_store/jij2009/anaconda/bin
for i in "$@"
do
case $i in
    -i=*|--input=*)
    INPUTFILE="${i#*=}"  # Input file which is an RData file containing phenotypes/genotypes/covars
    printf "[option -i |--input ] Input file = %s \n" "$INPUTFILE"
    shift
	;;
    -b=*|--batch=*)
    N_BATCH="${i#*=}"  
    printf "[option -b |--batch ] Number of Batches = %s \n" "$N_BATCH"
    shift
    ;;
    -v=*|--var=*)
    VAR="${i#*=}"  
    printf "[option -v |--var ] Percent Variance = %s \n" "$VAR"
    shift
    ;;
    -c=*|--subjobcores=*)
    SUBJOBCORES="${i#*=}"  
    printf "[option -c |--subjobcores ] Cores for each subjob = %s \n" "$SUBJOBCORES"
    shift
    ;;
    -m=*|--memory=*)
    MEM="${i#*=}"  
    printf "[option -m |--memory ] Memory for each core = %s \n" "$MEM"
    shift
    ;;
    -n=*|--ngpcs=*)
    NGPCS="${i#*=}"  
    printf "[option -n |--ngpcs ] Number of genotype PCs to use = %s \n" "$NGPCS"
    shift
    ;;
esac
done
# Default batch size

DATANAME=${INPUTFILE%%.h5}
SPLITREPO=/zenodotus/dat01/mezeylab_scratch/jij2009/temp_xqtl_split/

ARRAY=(0 "CONFETI" "ICE" "PANAMA"  "PCALMM" "CONPANA" "LINEAR" "PCAKMX" "RANDOM"  "GENOCOV")
#            1        2         3       4         5        6       7         8             9
METHOD=${ARRAY[$SGE_TASK_ID]} # Get Method

if [ "$METHOD" == "LINEAR" ]; then
    METHODVAR=$METHOD
elif [ "$METHOD" == "ICE" ]; then
    METHODVAR=$METHOD
elif [ "$METHOD" == "GENOCOV" ]; then
    METHODVAR=$METHOD
else
    METHODVAR=$METHOD$VAR
fi

PREFIXMX=$DATANAME"_"$METHODVAR"Rgpca"
PREFIX=$DATANAME"_"$METHODVAR
PVALH5=$PREFIX"_pvals.h5"


printf "Method for correction = %s \n" "$METHODVAR"

# Specify location and name of input file
INPUTPATH=/zenodotus/dat01/mezeylab_scratch/jij2009/eqtl_input_h5/
QSUBSCRIPT=$HOME"/eqtl_qsub_scripts/qsub_R_xqtl_genopc_modular.sh"
HITLISTSCRIPT=$HOME"/eqtl_multi_method/eqtl_hit_identification.sh"
# Specify outputpath and sub result folder for saving results
OUTPUTPATH=/zenodotus/dat01/mezeylab_scratch/jij2009/R_speedup_results/
MERGEDOUTPUT=$OUTPUTPATH"eqtl_hits/"
RESULTFOLDER=$DATANAME"_RGPCAresult/"
CISDISTANCE=1000000
PVALMETHOD="BH"
CUTOFF=0.05


# Specify outputpath and sub result folder for saving results

if [ "$DATANAME" == "Smith2008" ]; then 
		CISDISTANCE=10000
fi

# the  -p option will create all the necessary directories for the path and will do nothing if it already exists
mkdir -p $OUTPUTPATH/$RESULTFOLDER || exit 1
mkdir -p $MERGEDOUTPUT || exit 1
# change directory into the temporary space generated by the script
cd $TMPDIR


printf "Copying scripts and input data for analysis \n"

cp -v $INPUTPATH/$INPUTFILE .
cp -v $HOME/eqtl_multi_method/eqtl_Kmx_variance_h5.R .
cp -v $HOME/eqtl_multi_method/eqtl_geno_pca_calc.R .
cp -v $HOME/eqtl_multi_method/PANAMA_mx_var.py .
cp -v $HOME/eqtl_multi_method/eqtl_split_dataset.py .
cp -v $HOME/eqtl_multi_method/eqtl_combine_pvalues.py .

# run regression or mixed model analysis

# check whether Kmx is saved or not
printf "Estimating Missing Similarity Matrices"
$RPATH/Rscript-3.2.0 eqtl_Kmx_variance_h5.R $INPUTFILE $METHOD $VAR
# skipping generation  $PYTHONPATH/python PANAMA_mx_calculation.py -i $INPUTFILE

printf "Running xqtl python script to calculate p-values"
$PYTHONPATH/python PANAMA_mx_var.py -i $INPUTFILE -m $METHOD -v $VAR

printf "Running Genotype PCA calculations"
$RPATH/Rscript-3.2.0 eqtl_geno_pca_calc.R $INPUTFILE

echo "Splitting Genotypes into sub batches"

$PYTHONPATH/python eqtl_split_dataset.py -i $INPUTFILE -b $N_BATCH

if [ "$METHOD" == "LINEAR" ]; then
    METHODVAR=$METHOD
elif [ "$METHOD" == "ICE" ]; then
    METHODVAR=$METHOD
else
    METHODVAR=$METHOD$VAR
fi

mkdir -p $TMPDIR"/"$DATANAME"/$METHODVAR/"
cp -v $INPUTFILE $TMPDIR"/"$DATANAME"/$METHODVAR/"

rsync -vrh $TMPDIR/$DATANAME $SPLITREPO

H5FILEPATH=$SPLITREPO"/"$DATANAME"/$METHODVAR/"
# Specify outputpath and sub result folder for saving results
PVALUESUBSETPATH=$SPLITREPO"/"$DATANAME"/pval_subsets/"

mkdir -p $PVALUESUBSETPATH

STARTTIME=$(date)
echo "eQTL Analysis Start Time = $STARTTIME"

qsub -t 1-$N_BATCH -N $DATANAME -pe smp $SUBJOBCORES -sync y \
                   -l "os=rhel6.3, zeno=true, h_vmem=$MEM"\
                   $QSUBSCRIPT \
                   -F "-i=$INPUTFILE" \
                   -F "-m=$METHODVAR" \
                   -F "-p=$H5FILEPATH" \
                   -F "-o=$PVALUESUBSETPATH"\
                   -F "-g=$NGPCS"
ENDTIME=$(date)
echo "eQTL Analysis End Time = $ENDTIME"

PVALCOMBINEDPATH=$SPLITREPO"/"$DATANAME"/pval_combined/"

mkdir -p $PVALCOMBINEDPATH 

echo "Combining p-values"
# Aggregate p-values
$PYTHONPATH/python eqtl_combine_pvalues.py -i $INPUTFILE -p $PVALUESUBSETPATH -o $PVALCOMBINEDPATH 

COMBINEDPVALH5=$DATANAME"_"$METHODVAR"Rgpca_pvals.h5"

echo "Removing p-value subsets"
rm -r $PVALUESUBSETPATH

# run hitlist script
qsub -N $DATANAME$METHODVAR"hitlist" $HITLISTSCRIPT \
        -F "-i=$INPUTFILE" \
        -F "-p=$COMBINEDPVALH5" \
        -F "-d=$H5FILEPATH" \
        -F "-l=$PVALCOMBINEDPATH" \
        -F "-c=$CUTOFF" \
        -F "-e=$CISDISTANCE" \
        -F "-o=$OUTPUTPATH"