#! /bin/bash 
#$ -m ea  
#$ -M jinhyun.ju@gmail.com
#$ -q *@@red
#$ -j y
#$ -cwd
#$ -pe smp 16
#$ -l "os=rhel6.3, zeno=true, h_vmem=20G"

# Specifying os=rhel6.3 is important to have all the dependencies
# zeno = true uses only the nodes that are connected to the zenodotus file system

# $NODE ls /lib*/readl code to check if readline library is installed on a specific node
# no need to use unless you are not specifying the platform
DEFAULT_R_VERSION=3.2.0
RPATH=/zenodotus/dat01/mezeylab_store/mezeysoft/bin/
PYTHONPATH=/zenodotus/dat01/mezeylab_store/jij2009/anaconda/bin

# Default batch size
N_BATCH=20

printf "Checking input options \n \n"
# Getting option parameters
for i in "$@"
do
case $i in
    -i=*|--input=*)
    INPUTFILE="${i#*=}"  # Input file which is an RData file containing phenotypes/genotypes/covars
    printf "[option -i |--input ] Input file = %s \n" "$INPUTFILE"
    shift
		;;
    -b=*|--batch=*)
    N_BATCH="${i#*=}"  
    printf "[option -b |--batch ] Number of Batches = %s \n" "$N_BATCH"
    shift
    ;;
esac
done

# Array job method list
# Array job method list
ARRAY=(0 "CONFETI" "ICE" "PANAMA"  "PCALMM" "CONPANA" "LINEAR" "RANDOM"  )
#            1        2         3       4         5        6       7         8             9
METHOD=${ARRAY[$SGE_TASK_ID]} # Get Method

# Specify location and name of input file
INPUTPATH=/zenodotus/dat01/mezeylab_scratch/jij2009/eqtl_input_h5/
OUTPUTDIR=${INPUTFILE%%.h5}

# generates appropriate prefix 
DATANAME=${INPUTFILE%%.h5}


VAR=95

if [ "$METHOD" == "LINEAR" ]; then
    METHODVAR=$METHOD
elif [ "$METHOD" == "ICE" ]; then
    METHODVAR=$METHOD
else
    METHODVAR=$METHOD$VAR
fi

PREFIXMX=$DATANAME"_"$METHODVAR"py"
PREFIX=$DATANAME"_"$METHODVAR
PVALH5=$PREFIX"_pvals.h5"

printf "Method for correction = %s \n" "$METHODVAR"

# Specify outputpath and sub result folder for saving results
OUTPUTPATH=/zenodotus/dat01/mezeylab_scratch/jij2009/confeti_paper_results/
MERGEDOUTPUT=/zenodotus/dat01/mezeylab_scratch/jij2009/confeti_paper_results/eqtl_hits/
RESULTFOLDER=$OUTPUTDIR"_pyresult/"
CISDISTANCE=1000000
PVALMETHOD="BH"
CUTOFF=0.05


if [ "$DATANAME" == "Smith2008" ]; then 
		CISDISTANCE=10000
fi

# the  -p option will create all the necessary directories for the path and will do nothing if it already exists
mkdir -p $OUTPUTPATH/$RESULTFOLDER || exit 1

# change directory into the temporary space generated by the script
cd $TMPDIR


printf "Copying scripts and input data for analysis \n"

cp -v $INPUTPATH/$INPUTFILE .
cp -v $HOME/eqtl_multi_method/xqtl_python.py .
cp -v $HOME/eqtl_multi_method/eqtl_add_hit_information_h5.R .
cp -v $HOME/eqtl_multi_method/pval_rank_list.py .
cp -v $HOME/eqtl_multi_method/pval_median_extract.py .
cp -v $HOME/eqtl_multi_method/eqtl_Kmx_variance_h5.R .
cp -v $HOME/eqtl_multi_method/PANAMA_mx_var.py .
cp -v $HOME/jin/xqtl/* .
#cp -v $HOME/eqtl_multi_method/fastqq.cpp .
#cp -v $HOME/eqtl_multi_method/pval_bigmatrix_qqplot.R .
#cp -v $HOME/eqtl_multi_method/h5_to_bigmatrix_pvals.R .

# run regression or mixed model analysis

# check whether Kmx is saved or not
printf "Estimating Missing Similarity Matrices"
$RPATH/Rscript-3.2.0 eqtl_Kmx_variance_h5.R $INPUTFILE $METHOD $VAR
# skipping generation  $PYTHONPATH/python PANAMA_mx_calculation.py -i $INPUTFILE

printf "Running xqtl python script to calculate p-values"
$PYTHONPATH/python PANAMA_mx_var.py -i $INPUTFILE -m $METHOD -v $VAR

STARTTIME=$(date)
echo "$STARTTIME - Analysis start time"

$PYTHONPATH/python xqtl_python.py -i $INPUTFILE -m $METHODVAR -c $OMP_NUM_THREADS -b $N_BATCH

BHCALCTIME=$(date)
echo "$BHCALCTIME - Hit list script start time"

# Get significant hits
$RPATH/Rscript-3.2.0 hit_list_h5.r $PREFIXMX "bh" 0.1

$PYTHONPATH/python pval_median_extract.py -i $PREFIXMX"_pvals.h5"

# creating eqtl_merged subdirectory inside TMPDIR for organization

mkdir -p $TMPDIR/eqtl_merged/
EQTLMERGED=$TMPDIR/eqtl_merged/

MERGEDTIME=$(date)
echo "$MERGEDTIME - eQTL merged script start time"

# create eqtl_merged_df 
$RPATH/Rscript-3.2.0 eqtl_add_hit_information_h5.R $CISDISTANCE $INPUTFILE $EQTLMERGED

# mkdir -p $TMPDIR/qqplot/

# add qqplot generation
# for f in *.desc;
# do
#    $RPATH/Rscript-3.2.0 pval_bigmatrix_qqplot.R $f $TMPDIR/qqplot/
# done

rm -v $INPUTFILE

ENDTIME=$(date)
echo "$ENDTIME - Process complete"
echo "Copying results to scratch storage"

mkdir -p $OUTPUTPATH/Kmx/

cp -v *Kmx.h5 $OUTPUTPATH/Kmx/
cp -v *median.h5 $OUTPUTPATH/pval_medians/
cp -v *.txt $OUTPUTPATH/$RESULTFOLDER
#cp -v *.bin $OUTPUTPATH/$RESULTFOLDER
#cp -v *.desc $OUTPUTPATH/$RESULTFOLDER
cp -v $TMPDIR/eqtl_merged/*.h5 $MERGEDOUTPUT
#cp -v $TMPDIR/eqtl_merged/*sig_hits_map.pdf $OUTPUTPATH/Figures/sig_map/
#cp -v $TMPDIR/eqtl_merged/*cis_trans_cumulative.pdf $OUTPUTPATH/Figures/cumulative_cistrans/
# cp -v $TMPDIR/qqplot/* $OUTPUTPATH/Figures/qqplots/ 


